Update hashtocurve.sage
- fix  bug 
```(Integer(0), Integer(0), Integer(0), A, B) = E.a_invariants()
SyntaxError: cannot assign to function call
```
- update pyblake2 to Cryptodome.Hash.BLAKE2b, because pyblake2 is not working on Mac M1